cursed: floorgenerator.c heatmap.c main.c saveloader.c homemadeq.c enemies.c
	gcc -o cursed floorgenerator.c heatmap.c main.c saveloader.c homemadeq.c enemies.c -g -Wall -Werror -lcurses -lm
clean: enemy
	rm -f cursed
