enemies: floorgenerator.c heatmap.c main.c saveloader.c homemadeq.c enemies.c
	gcc -o enemy floorgenerator.c heatmap.c main.c saveloader.c homemadeq.c enemies.c -lm -g -Wall -Werror
clean: enemy
	rm -f enemy
